### ISSUE TITLE
Cant catch the StorageException when the file does not exist.

### ISSUE THREAD

**Issue by hemangjoshi37a** [mattreid1/firebase_image#1]
There is no exception named StorageException to catch the exception if there is no file located on that location.
Please help.

**Comment by mattreid1** [comment]
If you would like to, feel free to create a pull request!

**Comment by mattreid1** [comment]
Alternatively, can you send me your code and instructions to reproduce this error and I can have a look at it?

**Comment by mattreid1** [comment]
Closed due to inactivity.

**Comment by mocha234** [comment]
Hello @mattreid1 , rookie programmer here. Thanks for making this package. With my knowledge, I don't think I'm able to contribute, by the way, is there any way to catch StorageException with current version? Thanks..
