### ISSUE TITLE
Cannot fetch image with space in the name

### ISSUE THREAD

**Issue by psimondk** [mattreid1/firebase_image#10]
## Expected Behaviour
Image fetched

## Actual Behaviour
Throws: StorageException has occurred. Object does not exist at location

## Steps to Reproduce the Problem
  1. Upload image to storgae with a space in the name
  2. Try to retrieve it

## Additional Context
*Yeah I know, but a co-worker uploaded a bunch of images some of which have a space in the name - sic :)*

**Comment by mattreid1** [comment]
Is this a Firebase/GCP issue?

**Comment by ycv005** [comment]
In your firebase storage, store the file name with `_`. and then it will work. Now, query with whitespace, you will get result back.

**Comment by mattreid1** [comment]
I'm going to close this as I think this is more of a Firebase issue
