### ISSUE TITLE
How's this different then cached_network_image?

### ISSUE THREAD

**Issue by feinstein** [mattreid1/firebase_image#12]
Sorry this is more a question than an actual bug, but how does this package differ from [cached_network_image](https://pub.dev/packages/cached_network_image)?

Currently I am using `cached_network_image`, getting the download URL of my Firebase Storage images.

Is it just about how it checks the metadata for file updates?

**Comment by wizawuza** [comment]
@feinstein 
It's not obvious to me, but does `cached_network_image` check metadata and then re-download the image automatically if the metadata has changed?

**Comment by feinstein** [comment]
I don't think it will check any firebase specific Metadata.

**Comment by wizawuza** [comment]
That's what I thought when I looked their their docs. For me, this is worthwhile to use `firebase_image` as I have periodic changes to the images.

**Comment by wizawuza** [comment]
Nevermind, I just realized that firebase storage changes the download url (via the token) with each new upload, even if you overwrite. So with a new upload, you get a URL, and effectively invalidate the cache! Thanks for the suggestion.

**Comment by feinstein** [comment]
Yes, but you will have to keep track of the URL, this library on the other hand allows to fetch directly from image objects references, if I remember correctly.

**Comment by wizawuza** [comment]
I just made a wrapper with a FutureBuilder like this, so no more problems!

```
class FBImage extends StatelessWidget {
  final String imagePath;
  final double width;
  final double height;
  const FBImage({
    @required this.imagePath,
    this.width,
    this.height
  });

  Future<CachedNetworkImage> _futureGetter() async {
    final StorageReference storageReference = FirebaseStorage().ref();
    try {
      final String url = await storageReference.child(imagePath).getDownloadURL();
      return CachedNetworkImage(
        imageUrl: url,
      );
    } catch(e) {
      return null;
    }
  }

  @override
  Widget build(BuildContext context) {
    return FutureBuilder(
      future: _futureGetter(),
      builder: (BuildContext context, AsyncSnapshot<CachedNetworkImage> metaData) {
        if(metaData.hasData) {
          return SizedBox(
            width: width,
            height: height,
            child: metaData.data,
          );
        } else {
          return SizedBox(
            width: width,
            height: height,
            child: Container(
              color: Colors.grey.withOpacity(0.5),
            ),
          );
        }
      },
    );
  }
}
```

**Comment by feinstein** [comment]
I don't this this is the place for this, it will deviate from my original question.

That being said, don't return `CachedNetworkImage`, as its a Widget, return the URL `String` and then pass it inside the `FutureBuilder` to the `CachedNetworkImage`.

**Comment by wizawuza** [comment]
Agreed re: not the place. Thank you for the feedback.
