### ISSUE TITLE
BY_METADATA_DATE

### ISSUE THREAD

**Issue by lextotan** [mattreid1/firebase_image#17]
when i was upload my profile image its showing true but exit app and reopen app still showing old photo and after i m trying exit app re open coming true photo.its not working properly. and no showing error.

FirebaseImage("gs://*************/${*********}/profileUrl",cacheRefreshStrategy: CacheRefreshStrategy.BY_METADATA_DATE,shouldCache: true)

## Specifications
  - Version: *
  - Device: lg g4
  - Platform: Android
  - Flutter Version: * 1.20.2,

**Comment by mattreid1** [comment]
Try removing all the parameters besides "gs://****/${}/profileUrl" as the ones you have specified are default anyway...

Is there anything logged whatsoever?

**Comment by lextotan** [comment]
i did , but still same problem.

LOG:
09-15 00:42:05.899 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:10.722 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:10.900 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:11.733 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:15.229 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:15.229 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1324: Failed to get TransState, rc 
09-15 00:42:15.229 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:15.901 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:18.391 1573-1573/? D/PowerManagerServiceAO: updateWakeLockSummaryLocked: checkScreenWakelockList : mBaseService.mWakefulness=Awake, mBaseService.mWakeLockSummary=0x0
09-15 00:42:20.903 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:21.072 2849-3307/? I/[SystemUI]NetworkController: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) }
09-15 00:42:21.073 2849-3307/? I/[SystemUI]WifiSignalController: mWifiConnected = true, mWifiLevel = 2
09-15 00:42:21.081 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:21.081 2849-3307/? I/[SystemUI]MPTCP: updateMptcpState, mMptcpIconVisible = false, mDataNetType = 13
09-15 00:42:21.085 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:23.009 1573-2723/? V/AlarmManager: ELAPSED_WAKEUP set : Alarm{9c84f4 tag *walarm*:android.content.syncmanager.SYNC_ALARM type 2 when 303087738 android} when 303087738
09-15 00:42:23.018 1573-1677/? D/PowerManagerServiceAO: updateWakeLockSummaryLocked: checkScreenWakelockList : mBaseService.mWakefulness=Awake, mBaseService.mWakeLockSummary=0x0
09-15 00:42:24.529 1573-2654/? D/sensors_hal_Time: time_service_sensor1_cb: msg_type 2
09-15 00:42:24.529 1573-2654/? D/sensors_hal_Time: time_service_sensor1_cb: Sn 24, msg Id 3, txn Id 0
09-15 00:42:24.529 1573-2654/? D/sensors_hal_Time: tsOffsetIs: Apps: 303089264353342; DSPS: 1337706872; Offset : 262265690379463 (diff 4479 @4)
09-15 00:42:25.170 2849-2849/? D/KeyguardUpdateMonitor: Intent.ACTION_BATTERYEX_CHANGED EXTRA_CHARGING_CURRENT : 0 / EXTRA_HVDCP_TYPE : false
09-15 00:42:25.170 2849-2849/? I/[SystemUI]LGPowerUI: onReceive = com.lge.android.intent.action.BATTERYEX
09-15 00:42:25.170 2849-2849/? I/[SystemUI]LGPowerUI: levelEx = 100, plugTypeEx = 2, WirelessAlignment = 0, chargingCurrent = 0, orientation = PORTRAIT
09-15 00:42:25.170 2849-2849/? I/[SystemUI]LGPowerUI: On Skip Timer : true
09-15 00:42:25.175 1573-1784/? D/PowerManagerServiceAO: updateWakeLockSummaryLocked: checkScreenWakelockList : mBaseService.mWakefulness=Awake, mBaseService.mWakeLockSummary=0x0
09-15 00:42:25.177 2849-2849/? D/KeyguardUpdateMonitor: Intent.ACTION_BATTERY_CHANGED status : 5 ,plugged : 2 ,level : 100 ,temperature : 227
09-15 00:42:25.178 2849-2849/? I/[SystemUI]LGPowerUI: onReceive = android.intent.action.BATTERY_CHANGED
09-15 00:42:25.178 2849-2849/? I/[SystemUI]LGPowerUI: level = 100, plugType = 2, plugged = true, mCharging = false, temperature = 227
09-15 00:42:25.179 3399-3737/? D/LEDHandler: ACTION_BATTERY_CHANGED : plugged type=2
09-15 00:42:25.179 3399-3737/? D/LEDHandler: Battery Level Remaining: 100%
09-15 00:42:25.179 3399-3737/? D/LEDHandler: Battery Temp: 227, mChargingStatus=5, mChargingStop=false
09-15 00:42:25.180 1573-3563/? V/LGSettingsProvider: getSystemSetting(power_save_mode_enabled, -2)
09-15 00:42:25.184 3580-3580/? D/Telephony: PhoneApp: onReceive: android.intent.action.BATTERY_CHANGED
09-15 00:42:25.187 3697-3697/? W/MainApplication: onReceive intent : Intent { act=android.intent.action.BATTERY_CHANGED flg=0x60000010 (has extras) }
09-15 00:42:25.239 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:25.240 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1324: Failed to get TransState, rc 
09-15 00:42:25.240 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:25.904 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:27.125 2849-3307/? I/[SystemUI]NetworkController: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) }
09-15 00:42:27.126 2849-3307/? I/[SystemUI]WifiSignalController: mWifiConnected = true, mWifiLevel = 3
09-15 00:42:27.134 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:27.135 2849-3307/? I/[SystemUI]MPTCP: updateMptcpState, mMptcpIconVisible = false, mDataNetType = 13
09-15 00:42:27.139 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:28.788 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:29.802 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:30.150 2849-3307/? I/[SystemUI]NetworkController: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) }
09-15 00:42:30.150 2849-3307/? I/[SystemUI]WifiSignalController: mWifiConnected = true, mWifiLevel = 2
09-15 00:42:30.157 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:30.157 2849-3307/? I/[SystemUI]MPTCP: updateMptcpState, mMptcpIconVisible = false, mDataNetType = 13
09-15 00:42:30.161 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:30.905 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:33.182 2849-3307/? I/[SystemUI]NetworkController: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) }
09-15 00:42:33.183 2849-3307/? I/[SystemUI]WifiSignalController: mWifiConnected = true, mWifiLevel = 3
09-15 00:42:33.192 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:33.192 2849-3307/? I/[SystemUI]MPTCP: updateMptcpState, mMptcpIconVisible = false, mDataNetType = 13
09-15 00:42:33.197 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:35.251 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:35.251 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1324: Failed to get TransState, rc 
09-15 00:42:35.251 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:35.907 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:40.835 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:40.907 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:41.842 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:44.533 1573-2654/? D/sensors_hal_Time: time_service_sensor1_cb: msg_type 2
09-15 00:42:44.533 1573-2654/? D/sensors_hal_Time: time_service_sensor1_cb: Sn 24, msg Id 3, txn Id 0
09-15 00:42:44.533 1573-2654/? D/sensors_hal_Time: tsOffsetIs: Apps: 303109268007137; DSPS: 1338362352; Offset : 262265690371122 (diff 4531 @4)
09-15 00:42:44.851 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:45.261 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:45.262 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/MainCore.cpp:1324: Failed to get TransState, rc 
09-15 00:42:45.262 504-504/? I/Gobi: vendor/qcom/proprietary/RIDL/RIDLClient/RIDLSQL.cpp:1975: GetTransState() EBADF
09-15 00:42:45.278 2849-3307/? I/[SystemUI]NetworkController: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) }
09-15 00:42:45.279 2849-3307/? I/[SystemUI]WifiSignalController: mWifiConnected = true, mWifiLevel = 2
09-15 00:42:45.284 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:45.284 2849-3307/? I/[SystemUI]MPTCP: updateMptcpState, mMptcpIconVisible = false, mDataNetType = 13
09-15 00:42:45.289 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:45.909 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:46.861 2849-2849/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:47.856 622-622/? I/MSM-irqbalance: Decided to move IRQ163 from CPU1 to CPU3
09-15 00:42:48.304 2849-3307/? I/[SystemUI]NetworkController: onReceive: intent=Intent { act=android.net.wifi.RSSI_CHANGED flg=0x4000010 (has extras) }
09-15 00:42:48.306 2849-3307/? I/[SystemUI]WifiSignalController: mWifiConnected = true, mWifiLevel = 3
09-15 00:42:48.312 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:48.313 2849-3307/? I/[SystemUI]MPTCP: updateMptcpState, mMptcpIconVisible = false, mDataNetType = 13
09-15 00:42:48.316 2849-3307/? I/[SystemUI]MPTCP: showMptcpIcon, roaming
09-15 00:42:50.910 446-600/? E/ThermalEngine: ==== Enter sched_bmhb_cs_gov -> vs_temp = 23 ===
09-15 00:42:52.856 622-622/? I/MSM-irqbalance: Decided to move IRQ222 from CPU3 to CPU2
![image](https://user-images.githubusercontent.com/62778717/93148727-7bebff00-f6ec-11ea-9ddc-f1560faa7f3a.png)

**Comment by lextotan** [comment]
if you want see. i can record a video.

**Comment by lextotan** [comment]
solved

**Comment by rdonoso** [comment]
hi, how do you solved it? i am having the same issue

**Comment by lextotan** [comment]
actually not , i ll write my cache images class.

**Comment by lextotan** [comment]
i think problem is , 
when u do first upload fetching from firebase and showing no problem after second try showing from cache . it has to be same time run cacheimage=FirebaseImageObject. So cacheimage variable not equal first time new image.
Image cacheimage;
method(){
FirebaseImageObject();
cacheimage=FirebaseImage;
}
Showing image

**Comment by rdonoso** [comment]
mmm it should be a way to add a method to flush the cache of that url inside the library of FirebaseImage, what do you think?

**Comment by lextotan** [comment]
yes i found, https://pub.dev/packages/cached_network_image
