### ISSUE TITLE
Manually force cache flush or reset.

### ISSUE THREAD

**Issue by jbryanh** [mattreid1/firebase_image#19]
Any thoughts to a method for flushing the cache to refresh the file?  Perhaps this is already self evident to most.  i'm just a novice coder.  Thanks for the tool.  It's helpful!

**Comment by janlektonen** [comment]
It seems that cache is no longer working. I use latest updates from Firebase.
If I state that "shouldCache: false" then I still get the old image from storage even though I have overwritten it with a new image and can also see that Created and Modified dates are updated in Storage.

If I restart my app (NOT hot-reload) then it seems to get the new image... ? But normal use of app does not use this approach.

Please check this issue as this is why I use your package... and cache seems to broken...

Thanks for great work, Jan

**Comment by janlektonen** [comment]
I will create a new issue for this now.. if you want you can delete this one.

**Comment by jbryanh** [comment]
I'm closing this issue as @janlektonen created a new one with a better explanation.
