### ISSUE TITLE
Resolve Incompatibility with firebase_storage ^5.0.0

### ISSUE THREAD

**Issue by jbryanh** [mattreid1/firebase_image#21]
Firebase Storage was upgraded.  Can we get this bumped to get compatible?

Because firebase_image 0.2.0 depends on firebase_storage ^4.0.0 and no versions of firebase_image match >0.2.0 <0.3.0, firebase_image ^0.2.0 requires firebase_storage ^4.0.0.
So, because <AnyApp> depends on both firebase_storage ^5.0.0 and firebase_image ^0.2.0, version solving failed.
pub get failed (1; So, because <AnyApp> depends on both firebase_storage ^5.0.0 and firebase_image ^0.2.0, version solving failed.)

**Comment by morphy2k** [comment]
Should be fixed with #20 

Hope it will be merged very soon.

**Comment by mattreid1** [comment]
Going to publish to pub.dev now!
