### ISSUE TITLE
In my flutter application user has to submit or upload 3 images and 2 PDFs randomly.

### ISSUE THREAD

**Issue by srk2k13** [mattreid1/firebase_image#25]
In my flutter application user has to submit or upload 3 images and 2 PDFs randomly in each form.
When the user opens the retrieved page or home screen,the user should be always able to see the saved or uploaded or retrieved images .

Those PDFs and images should remain permanent.

Please fix my issue How to achieve this functionality.

**Comment by mattreid1** [comment]
That's not possible as the way the caching mechanism works means that the images are stored in the systems temporary directory in order that system can clear it if it needs more space.
