### ISSUE TITLE
Feature request: easy way to pre-cache by url

### ISSUE THREAD

**Issue by lukepighetti** [mattreid1/firebase_image#26]
We'd love to be able to fire off a command to pre-cache a Firestore image url.

ie

```dart
final url = "gs://vgl-xxxa.appspot.com/users/xxxxx/avatars/xx-xx-xx-a2fb-xx.jpg";
FirebaseImageCacheManager.precache(url);
```

**Comment by yelkamel** [comment]
that should be great

**Comment by lukepighetti** [comment]
@mattreid1 if you can recommend a strategy to implement this I will get it done and make a PR

**Comment by mattreid1** [comment]
In one of my tests I actually run something like this if I'm not mistaken....

```dart
void setBytes() async {
  Uint8List imageBytes =
      (await FirebaseImage('gs://xxxxxxxxx.appspot.com/xxxx.jpg')
          .getBytes()); // This fetches the image 

  setState(() {
    bLength = imageBytes.length;
  });
}
```

Would something like this achieve what you need?

**Comment by lukepighetti** [comment]
Check the PR I made, #27

**Comment by mattreid1** [comment]
Take a look at the PR I just made #33.

It's async, avoids logic duplication, very simple, null safe and throws a descriptive error if the developer has accidentally disabled caching.

You can use it by calling this anywhere in the code.

```dart
FirebaseImage('gs://xxxxxxxxx.appspot.com/xxxx.jpg').preCache();
```

Might be worth me disabling the max file size limit for pre-caches (or setting it high e.g. 50MB). Thoughts?

If you're happy this solves the issue, I'll publish this.

**Comment by lukepighetti** [comment]
I'm not able to test it right this moment but if that does cache the image so it's instant retrieval the next time you make a FirebaseImage with that URL than I much prefer your solution and I'd be happy for my PR and this issue to be closed.
