### ISSUE TITLE
Update Firebase dependency

### ISSUE THREAD

**Issue by ycv005** [mattreid1/firebase_image#29]
Hey, please update the firebase dependency.
@mattreid1 @thearaks @awhitford 
 Thanks in advance.

**Comment by awhitford** [comment]
Looks like PR #32 is already submitted. @mattreid1 needs to accept it.

**Comment by awhitford** [comment]
Actually, PR #30 looks a little better.

**Comment by mattreid1** [comment]
Fixed by #30.
