### ISSUE TITLE
update dependencies

### ISSUE THREAD

**Issue by tetoL44** [mattreid1/firebase_image#54]
update firebase_storage to ^10.0.0

**Comment by jbryanh** [comment]
@mattreid1 @thearaks @awhitford

**Comment by thearaks** [comment]
Please merge #55, thank you! ✌️

**Comment by ghost** [comment]
> Please merge #55, thank you! ✌️

I just downloaded yours and made local package out of it! Cheers buddy

**Comment by mattreid1** [comment]
Apologies for the delay, been a busy year. All updated now!
